In [1]:
import numpy as np
from tinygrad.helpers import Timing

In [2]:
from tinygrad import Tensor

In [3]:
t1 = Tensor([1,2,3,4,5,])
na = np.array([1,2,3,4,5,])
t2 = Tensor(na)

In [4]:
full = Tensor.full(shape=(2, 3), fill_value=5)
zeros = Tensor.zeros(2,3)
ones = Tensor.ones(2,3)

In [5]:
full_like = Tensor.full_like(full, fill_value=2)
zeros_like = Tensor.zeros_like(full)
ones_like = Tensor.ones_like(full)

In [6]:
from tinygrad import dtypes

t3 = Tensor([1,2,3,4,5], dtype=dtypes.int32)

In [7]:
t4 = Tensor([1,2,3,4,5])
t5 = (t4 + 1) *2
t6 = (t5 * t4).relu().log_softmax()

In [8]:
t5.numpy()

array([ 4,  6,  8, 10, 12], dtype=int32)

In [9]:
t6.numpy()

array([-56., -48., -36., -20.,   0.], dtype=float32)

In [10]:
from tinygrad import nn

In [11]:
class TinyNet:
  def __init__(self):
    self.l1 = nn.Linear(784, 128, bias=False)
    self.l2 = nn.Linear(128, 10, bias=False)
    
  def __call__(self, x):
    x = self.l1(x)
    x = x.leakyrelu()
    x = self.l2(x)
    return x
  
net = TinyNet()

In [12]:
from tinygrad.nn.optim import SGD

In [13]:
import tinygrad as tg

In [14]:
opt = SGD(nn.state.get_parameters(net), lr=3e-4)

In [15]:
from extra.datasets import fetch_mnist

In [16]:
from tinygrad import Tensor

In [19]:
from tinygrad import Device

In [22]:
a = Tensor.rand((10,2))
b = Tensor.rand((10,2))

In [24]:
a.numpy()

array([[0.1067183 , 0.2691685 ],
       [0.37456864, 0.59436184],
       [0.17465705, 0.8929456 ],
       [0.9467877 , 0.25182283],
       [0.16847748, 0.03468537],
       [0.904949  , 0.6656703 ],
       [0.04702169, 0.8145742 ],
       [0.6406311 , 0.8165203 ],
       [0.07719773, 0.02906275],
       [0.11048692, 0.944506  ]], dtype=float32)

In [25]:
a * b

<Tensor <LB CLANG (10, 2) float (<BinaryOps.MUL: 9>, None)> on CLANG with grad None>

In [32]:
print((a * b).lazydata.buffer)



<buf real:False device:CLANG size:20 dtype:dtypes.float offset:0>
